apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"php:8.0-ubi8","namespace":"openshift"},"fieldPath":"spec.template.spec.containers[?(@.name==\"php\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: esempio
      app.kubernetes.io/component: esempio
      app.kubernetes.io/instance: esempio
    name: esempio
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: esempio
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: esempio
      spec:
        containers:
        - image: ' '
          name: php
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: esempio
      app.kubernetes.io/component: esempio
      app.kubernetes.io/instance: esempio
    name: esempio
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: esempio
  status:
    loadBalancer: {}
kind: List
metadata: {}
